version: '3.8'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - webnet

  inventory-agent:
    build: ./stock_service/inventory_agent
    volumes:
      - ./stock_service/inventory_agent/src/app/migrations:/app/migrations  # Example path, adjust accordingly
    networks:
      - webnet

  customer-agent:
    build: ./customer_service
    volumes:
      - ./customer_service/src/app/migrations:/app/migrations  # Example path, adjust accordingly
    networks:
      - webnet

  auth:
    build: ./auth_service
    volumes:
      - ./auth_service/src/app/migrations:/app/migrations  # Example path, adjust accordingly
    networks:
      - webnet

  chain-layer:
    build: ./stock_service/chain_layer
    networks:
      - webnet

  data-layer:
    build: ./stock_service/data_layer
    networks:
      - webnet

networks:
  webnet:
