version: '3.8'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/
      - ./nginx/certbot/conf:/etc/letsencrypt/
    networks:
      - webnet

  inventory-agent:
    build: ./stock_service/inventory_agent
    networks:
      - webnet

  customer-agent:
    build: ./customer_service
    networks:
      - webnet

  auth:
    build: ./auth_service
    networks:
      - webnet

  chain-layer:
    build: ./stock_service/chain_layer
    networks:
      - webnet

  data-layer:
    build: ./stock_service/data_layer
    networks:
      - webnet

networks:
  webnet:
