version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - webnet

  inventory-agent:
    build: ./stock_service/inventory_agent
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://alicia:alicia@cloud_sql_proxy:3306/alicia
    networks:
      - webnet
      - sqlnet

  customer-agent:
    build: ./customer_service
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:alicia2134@cloud_sql_proxy:5432/postgres
    networks:
      - webnet
      - sqlnet

  auth:
    build: ./auth_service
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:alicia2134@cloud_sql_proxy:5432/postgres
    networks:
      - webnet
      - sqlnet

  chain-layer:
    build: ./stock_service/chain_layer
    networks:
      - webnet

  data-layer:
    build: ./stock_service/data_layer
    networks:
      - webnet

  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: >
      /cloud_sql_proxy -instances=alicia-415212:southamerica-east1:alicia-auth=tcp:5432,
      alicia-415212:us-central1:alicia-customer=tcp:5432,
      alicia-415212:us-central1:alicia-inventory=tcp:5432
    restart: on-failure
    networks:
      - sqlnet

networks:
  webnet:
  sqlnet:
